paths:
  raw_dir: "dataset/raw"
  split_output_dir: "dataset/splits/seed_42"

dataset:
  target_size: [224, 224]
  seed: 42
  classes:
    - aphids_pest
    - common_rust
    - fall_armyworm
    - gray_leaf_spot
    - healthy
    - nitrogen_deficiency
    - northern_corn_leaf_blight
    - phosphorus_deficiency
    - potassium_deficiency